runtime: nodejs
env: flex
env_variables:
  SQL_USER: "root"
  SQL_PASSWORD: ""
  SQL_DATABASE: "sigfood"
  INSTANCE_CONNECTION_NAME: "sigfood:asia-southeast2:sigfood"
beta_settings:
  cloud_sql_instances: "sigfood:asia-southeast2:sigfood"
